package team044;

public enum BuildOrderMessaging {
    BuildBeaverBuilder,
    BuildBeaverMiner,
    BuildBasher,
    BuildCommander,
    BuildComputer,
    BuildDrone,
    BuildScoutingDrone,
    BuildSupplyDrone,
    BuildSearchAndDestroyDrone,
    BuildLauncher,
    BuildMiner,
    BuildSoldier,
    BuildTank,
    BuildAerospaceLab,
    BuildBaracks,
    BuildHelipad,
    BuildMinerFactory,
    BuildTankFactory,
    BuildTechnologyInstitute,
    BuildTrainingField,
    BuildSupplyDepot,
    BuildMiningBaracks,
    BuildDefensiveSoldier,
    BuildDefensiveTank,
    BuildDefensiveBasher,
    BuildDefensiveLauncher,
    BuildMiningAeroSpaceLab,
    BuildHarrassSoldier,
    BuildHarrassBasher,
    BuildHarrassTank,
    BuildSquadTank,
    BuildSquadLauncher,
    BuildSquadSoldier,
    BuildSquadBasher,
    BuildSupportingSoldier,
    BuildFollowerSoldier,
    BuildFollowerDrone,
    // this should be last entry
    DoneBuilding
}
